name       : uqm
version    : 0.7.0
release    : 6
source     :
    - http://vorboss.dl.sourceforge.net/project/sc2/UQM/0.7/uqm-0.7.0-source.tgz : a3695c5f7f0be7ec9c0f80ec569907b382023a1fee6e635532bd53b7b53bb221
    - http://vorboss.dl.sourceforge.net/project/sc2/UQM/0.7/uqm-0.7.0-3domusic.uqm : c57085e64dad4bddf8a679a9aa2adf63f2156d5f6cbabe63af80519033dbcb82
    - http://vorboss.dl.sourceforge.net/project/sc2/UQM/0.7/uqm-0.7.0-content.uqm : b8f6db8ba29f0628fb1d5c233830896b19f441aee3744bda671ea264b44da3bf
    - http://vorboss.dl.sourceforge.net/project/sc2/UQM/0.7/uqm-0.7.0-voice.uqm : bcccf801b4ba37594ff6217b292744ea586ee2d447e927804842ccae8b73c979
license    :
    - CC-BY-2.0
    - CC-BY-NC-SA-2.5
    - GPL-2.0
component  : games.strategy
summary    : The Ur-Quan Masters - remake of Star Control II
description: |
    The Ur-Quan Masters - remake of Star Control II
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libmikmod)
    - pkgconfig(libpng)
    - pkgconfig(openal)
    - pkgconfig(SDL_image)
    - pkgconfig(vorbisfile)
setup      : |
    cp $pkgfiles/* ./
    sed -i "s|INSTALLDIR_PREFIX|$installdir/usr|" config.state
    sed -i "s|/usr|$installdir/usr|" build.vars
    #./build.sh uqm reprocess_config
    # fix build (Fedora)
    cd src/uqm/comm/
    for d in */ ; do
        cd $d
        mv strings.h ustrings.h
        cd ..
    done
    find . -type f -name '*.c' | xargs sed -i s/strings.h/ustrings.h/g
    find . -type f -name '*.h' | xargs sed -i s/STRINGS/USTRINGS/g
build      : |
    ./build.sh uqm
install    : |-
    ./build.sh uqm install
    for pkg in 3domusic content voice; do
        install -D -m 00644 $sources/uqm-$version-$pkg.uqm $installdir/usr/share/uqm/content/packages/uqm-$version-$pkg.uqm
    done
    install -D -m 00644 uqm.png $installdir/usr/share/pixmaps/uqm.png
    install -D -m 00644 uqm.desktop $installdir/usr/share/applications/uqm.desktop
